server {
    listen 80;
    server_name salud.cundinamarca.gov.co servicios-salud.creatisoftcolombia.lat medicocundinamarca.creatisoftcolombia.lat;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Reverse Proxy for Servicios Salud
    location /servicios-salud/ {
        proxy_pass http://servicios-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Reverse Proxy for Medicos
    location /medico-en-tu-territorio/ {
        proxy_pass http://medicos-app:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Expand to port 443 with logic for certbot once SSL is procured
server {
    listen 443 ssl;
    server_name salud.cundinamarca.gov.co servicios-salud.creatisoftcolombia.lat medicocundinamarca.creatisoftcolombia.lat;

    ssl_certificate /etc/letsencrypt/live/servicios-salud.creatisoftcolombia.lat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/servicios-salud.creatisoftcolombia.lat/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /servicios-salud/ {
        proxy_pass http://servicios-frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /medico-en-tu-territorio/ {
        proxy_pass http://medicos-app:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
